# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
    
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
   build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
   
      - name: pwd directory
        run: pwd
      
      - name: list folder 
        run: ls -la 
      
      - name: create secret_id_rsa 
        run: echo "${PRIVET_KEY}" > secret_id_rsa
      
      - name: chmod 0400 
        run: |
             chmod 0400 secret_id_rsa
           
      - name: list folder 
        run:  ls -la  
                 
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
      
      - name: Run playbook 
        uses: Hugozys/ansible-deploy@master
        with:
          directory: ./Ansible
          playbook: playbook_nginx.yaml
          ssh_key_file_name: secret_id_rsa
          verbose: 2 
     
