# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
    
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
   
      - name: pwd directory
        run: pwd
      
      - name: list folder  
        run: ls -la 
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          
      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
      # Required, playbook filepath
           playbook: playbook_nginx.yaml --user ubuntu --key-file ${{-----BEGIN RSA PRIVATE KEY-----
MIIEowIBAAKCAQEA4C2RClu69kNLQwP32rXSU87N4ZePgJDkwF89rGDSaUoE5rbW
ce2g4H9MQ2t9YHgqlxU3qugPtKP1GjyBbnkCro/gzKMk2LgfZv4ChdELUMILjPWK
8kWc0B0bkElM2vH2Or7oxAavQkmeeAzlhPGqVlAB2pWjZB4UjQ3+Rwo10SgeWJwO
8jWLdleVXe5ci/Gu88Qs9d5eAIQbRZef8cNcbMD1QOHKmpihMY8c4H0nQyRw4QOf
mfMm2W85d75Ephs1swYbAZEhd9D0U8i0gLUzdokq4B3mthMJJL2FWR/kMon6QaRA
hsNzhieM2hnDYLgaEFRigiqC49jcHiLyixlT9QIDAQABAoIBAB5ZDNGCKYU9ButD
lkIdayO9U1G+2sZk1xLT0d2MHe/y/UbeaZlyudyqXwChhI+StPFPBgI0+CtUJtIu
brct2pcXEy+gxlQwWM/wgxbqfcWo/zdN5kl18wyZZCncQnNBXjwFrC0dWox2uuU1
mbytmomkuxuENmJPUCjoRAwJ7c8qhlPw2CpvscmatPLGPrqRHeDKvRF/64TbL0qK
xMLA4ipVU8kaCUFq1e1FfU8VsshulzzNyflxfQ7yuwMzS2eaWUGxghWCJGcnNJZO
FvQ1Vsl9z6H3Cu+2eht4/GrbUDhL/Gagc6YY3+oxkxmOm0/h/0IOnngdD+bPtp1x
9epPgOECgYEA8akrkerOMOe9UKLMreZ9Qg5owK/FWCPL8GmAmZ+TmeOVfbjPe9NW
wvFoD6vJDRB1+8PvNxnlcdfIJNAAZq3LyHHCQzGadmhN4eu7z10OiDwASBeEolyD
MnlPbLRyQ9KpgtshFGqIoMmJX2OJlr5neT/sOZZgnYTF4/DFGmxTVtsCgYEA7XrV
A/mOtIvvByt1M9EWdhMLnVH1GR1kQNrgVggnxPtzFMcnPvtPC33rMJ9+uYfSPzrx
ljp4oOkwmpnwsRqKCPRQ5E5XVZzpdNDGG1Hs/PqwydwHATYz6YrK5YReXCxHSO0u
nqXo7s+A8G5vQTjmPINeN/ZOKoLdfTjkU37gcW8CgYAuu+qDI4eQiaBg8brnfoWG
usajTNq7OuD7s0t9ahDfV9XXJGBrr+k9dfYL4crVzfMjJzchzs5Cf9pi1B7fvIiG
UQmiePtIHs/A+xes+HARBJmBV5r80ytEHZWwjgzy9NB3T+1Lx3Z4scDxQ4yeLGBS
YHxMfrpcfArRFATqITzUtQKBgFQhDK+gzBZX8HDYy2d07gEcVCQCcdLY37g+EfVI
ZFZbQfSdbODaBLGshRIvnqQ5Ypk113oB8tQGaEqMuID1RutPKg0HV9cjhGz2vQfW
qR8h7FlGklCylAdrPN+8WfVLVmGWbMqVOgTIDAShCtbPQnkzjMBEiIJ04+RFsFWI
ABkPAoGBAN9DDnsD/j0hzbsgqUiMi4wHvuW57JuzVhGmProtaMpr5wCEyrfhLFPj
XGLO4lj0vjq6tfopQEw9d5JYRGiQGDSGB8Xk1Vdh515Hoj26M2ujDKK8X3x3ztVk
e9S26xjSLI9CLtdRkV4ZekCZu6UmvJSpcB1otIGHS+a2DY6+DTz3
-----END RSA PRIVATE KEY-----}} -e "key=~/.ssh/id_rsa.pub"
    # Optional, directory where playbooks live
           directory: ./Ansible
    # Optional, SSH private key
           mykeypair.pem : ${{secrets.SSH_PRIVATE_KEY}}
    # Optional, literal inventory file contents
         #  inventory: |
        #   [all]
        #     example.com

        #     [group1]
        #    example.com
    # Optional, SSH known hosts file content
        #   known_hosts: .known_hosts
    # Optional, encrypted vault password
           vault_password: ${{secrets.VAULT_PASSWORD}}
    # Optional, galaxy requirements filepath
           #requirements: galaxy-requirements.yml
    # Optional, additional flags to pass to ansible-playbook
         #  options: |
         #    --inventory .hosts
         #    --limit group1
         #    --extra-vars hello=there
          #   --verbose
