name: CI

on:
  push:
    branches: [ "main" ]
    
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
   build:
    runs-on: self-hosted
    
    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Hello, world!
   
      - name: pwd directory
        run: pwd
      
      - name: list folder 
        run: ls -la 
      
      - name: create secret_id_rsa 
        run: echo "${PRIVET_KEY}" > secret_id_rsa
      
      - name: chmod 0400 
        run: |
             chmod 0400 secret_id_rsa
           
      - name: list folder 
        run:  ls -la  
                 
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
      - name: Run Ansible playbook
        uses: dawidd6/action-ansible-playbook@v2.5.0
        with:
        # Required, playbook filepath
          playbook: playbook_nginx.yaml  
        # Optional, directory where playbooks live
          directory: ./Ansible
        # Optional, SSH private key
          key :  secret_id_rsa
        # Optional, literal inventory file contents
        # inventory: |
        #  [all]
         # example.com

          #[group1]
          
     # example.com
        # Optional, SSH known hosts file content
        #  known_hosts: known_hosts
    # Optional, encrypted vault password
  #  vault_password: ${{secrets.VAULT_PASSWORD}}
    # Optional, galaxy requirements filepath
  #  requirements: galaxy-requirements.yml
    # Optional, additional flags to pass to ansible-playbook
          options: |
             -v
     # - name: Run playbook 
     #   uses: Hugozys/ansible-deploy@master
     #   with:
    #    directory: ./Ansible
    #      playbook: playbook_nginx.yaml
    #      hosts: hosts.txt
    #      ssh_key_file_name: secret_id_rsa
    #      verbose: 1
     
