name: Build & Push Docker Image CI
#name: Build & Push Docker image with latest tag

on:
  push:
    branches: [ main ]
#on:
 # push:
  #   tags:
   #    - "v*,*,*"
  
jobs:
  build_and_push:

    runs-on: ubuntu-latest
        #- self-hosted
        #- label1  
    env:
      DOCKER_IMAGE_NAME: "andreysagurov/nginx_HELLOWORLD"
      DOCKER_LOGIN:       ${{ secrets.DOCKER_LOGIN }}
      DOCKER_PASSWORD:    ${{ secrets.DOCKER_PASSWORD }}
      
      
    steps:
    - uses: actions/checkout@v2
    - name: Set env
      run: echo "VERSION=${GITHUB_REF#refs/tags/*}" >> $GITHUB_ENV
    - name: Show environment variables
      run: |
        echo "DOCKER_IMAGE_NAME: ${DOCKER_IMAGE_NAME}"
        echo "VERSION: ${VERSION}"
    - name: Docker login
      run: docker login -u "${DOCKER_LOGIN}" -p "${DOCKER_PASSWORD}"
    - name: Build the Docker image
      run: docker build . --file Dockerfile -t "${DOCKER_IMAGE_NAME}:${{ env.Version }}"
    - name: Push the Docker image
      run: docker push "${DOCKER_IMAGE_NAME}:${{ env.Version }}"
