# This is a basic workflow to help you get started with Actions
name: My_githubActions
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  my_CI_CD:
  #build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
    - name: Run a one-line script
      run :  echo "Hello, world from testing new!"
      
    - name: pwd directory
      run: pwd
      
    - name: list folder  
      run: ls -la 
      
    - name: change directory
      run: cd /home/runner/work/Terraform_docker_ansible_aws/Ansible
   
  # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Check my repository
      uses: actions/checkout@v3
    
    - name: Run ansible nginx
      run: .Ansible/ansible-playbook playbook_nginx.yaml --user ubuntu --key-file mykeypair.pem -e "key=~/.ssh/id_rsa.pub"    
  
 #my_deploy:
 # runs-on: ubuntu-latest
 # needs: [ my_CI-CD ]
 
   #steps:
   #- name: Run a one-line script
   #   run: echo Hello, world!
 
      # Runs a set of commands using the runners shell
 #     - name: Run a multi-line script
  #      run: |
  #        echo Add other actions to build,
  #        echo test, and deploy your project.
