# This is a basic workflow to help you get started with Actions

name: My_githubActions

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
#  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
    - name: Run a one-line script
      run : echo "Hello, world from testing new!" 
  # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - Check my repository
      uses: actions/checkout@v3
    - name: Run ansible nginx
      run: ansible -playbook playbook_nginx.yaml --user ubuntu --key-file mykeypair.pem -e "key=~/.ssh /id?rsa/pub"    
  
my_deploy:
  runs-on: ubuntu-latest
  needs: [ my_CI-CD ]
  
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

  
      # Runs a set of commands using the runners shell
 #     - name: Run a multi-line script
  #      run: |
  #        echo Add other actions to build,
  #        echo test, and deploy your project.
